### ISSUE TITLE
안녕하세요. 

### ISSUE THREAD

**Issue by Taebu** [Kevin-Lee/napucon2016-weather-app#1]
저는 서버 엔지니어를 맡고 있습니다. 직장은 일산에 있는 앱제작 회사 `에이엔피알`(http://anpr.cafe24.com/)이라는 곳에 있습니다.

문태부 라고 합니다.

유투브에서 github 관련해서 인상 깊은 강의를 해주셔서 궁금한 점이 있어 문의 합니다.

이번에 보안 이슈로 centos 5.11 을 사용하여 tslv1을 막고 tslv1.2 를 지원 한다고 합니다.
https://githubengineering.com/crypto-removal-notice/

그래서 업데이트를 하려고 보니 centos 6.5에서만 tslv1.2 를 지원 한다고 합니다.

서버가 centos5.11 에 최적화 되어 있고 해당 작업을 하려면 재설치를 하는 등등  에 문제가 있어 기존에 2월 3일 이후로 한 커밋은 해당 centos 5.11 서버에 저장 되어 있고 해당 서버에 있는 데이터를 옮겨서 기존 대로 커밋 푸시 하려고 합니다.

이런 경우 어떻게 해결하시는지 조언을 얻고자 합니다.

**Comment by Taebu** [comment]
자문 자답 합니다. 
rsync라는게 있어서 해결 했습니다.

**Comment by kevin-lee** [comment]
@Taebu 이상하게 알림을 못 받아서 여기 글을 남기신줄 몰랐네요. rsync같은걸 쓰셔서 옮기셔도 되지만 앞으로 그런 과정을 편하게 하시려면, 서버 설치및 관리를 자동화 하시면 좋을거 같습니다. 요즘 자동화 관련 툴이 많이 나오고 있습니다만, 배우기 쉽고 접근성이 높은거 하나 추천 드리자면, Ansible이라는 도구가 있습니다. 나중에 관심 있으시면 한번 살펴 보시면 좋을거 같습니다.
